linux_gmp:
  stage: build
  script:
    - autoreconf -i
    - ./configure
    - make
    - make check
  tags:
    - linux

lucaschains:
  stage: build
  script:
    - git co lucaschains
    - autoreconf -i
    - ./configure
    - make
    - make check
  tags:
    - linux
